### ISSUE TITLE
PENTA_DEVROOMID, change due to vendoring?

### ISSUE THREAD

**Issue by Habbie** [meyskens/penta-export#4]
In revision 444719a9af6f7e952f1bdc2beb1bec9c6323c464, `PENTA_DEVROOM_ID` works, and leaving it out yields `2018/12/07 15:15:31 required key PENTA_DEVROOM_ID missing value`.

In revision f2cd6913b5b12ae93275eaabb8a4ff8b408654d2, I need to pass `PENTA_DEVROOMID` to get the right output, and leaving it out does not yield an error.

I'm not well versed in Go and vendoring, but did you vendor a different version than you depended on before?

**Comment by meyskens** [comment]
Will double check this for you!

**Comment by meyskens** [comment]
You're correct. I tried the new Go modules for this but it likes to pick it's own version. I will PR a patch in a moment.
